### ISSUE TITLE
FMU export in Dymola 2017

### ISSUE THREAD

**Issue by Ywatan** [modelica-3rdparty/ExternalMedia#11]
Hello, I am now using External Media Library in Dymola 2017 and trying to FMU export on my original model incorporating library External Media Library.
But, I cannot success creating FMU files. Is this library compatible with FMU creation?

**Comment by slamer59** [comment]
Hello,
**Can you provide an exemple and the error associated ?**
My guess is that Dymola does not include this library with FMU. 
ExternalMedia wrap a compiled library. So FMU needs this compiled library (.so or .lib/.dll)

FMU is a zipped container. You can open it and try to find a .lib/.so somewhere. If you don't see it try to add it manually. 

Regards

**Comment by casella** [comment]
This ticket is quite old now. Ywatan, please reopen with more details if this is still relevant for you. Thanks!
