### ISSUE TITLE
ThermodynamicState and SaturationProperties storage size of XX isn't konwn problem existing with setState funtion and setSat funtion

### ISSUE THREAD

**Issue by jiwucisha** [modelica-3rdparty/ExternalMedia#114]
When I was using MWorks software to open the Test of ExternalMedia for simulation, the following errors always occurred. May I ask what caused this?
![屏幕截图 2024-11-14 134722](https://github.com/user-attachments/assets/8832ac07-7f01-40a7-aa02-834078cf3d8a)
![屏幕截图 2024-11-14 134733](https://github.com/user-attachments/assets/ed442772-e647-4a40-99ac-68e8aef197b4)
![屏幕截图 2024-11-14 134806](https://github.com/user-attachments/assets/309e5bcf-fbbe-4b2e-ac23-43319410dd46)
![屏幕截图 2024-11-14 134821](https://github.com/user-attachments/assets/b69025bf-2059-43eb-9348-c7798d6df53c)

**Comment by jiwucisha** [comment]
> I also encountered the same problem. Have you solved it?

Are you also using Mworks?The CoolProps library has been updated in Mworks now. You can download the latest version to have a look. This media library is not very compatible with Mworks and is more suitable for software like OpenModelica.

**Comment by zhuzhu15304840391** [comment]
Yes, I'm currently using Mworks. I have the latest version of Mworks now. It contains the TYMEDIA library, but there are too few media files and they don't have what I need. This library does not seem to be well-suited for Mworks. Have you been able to solve the problem you encountered? Are you still using OpenModelica now?

> > I also encountered the same problem. Have you solved it?
> 
> Are you also using Mworks?The CoolProps library has been updated in Mworks now. You can download the latest version to have a look. This media library is not very compatible with Mworks and is more suitable for software like OpenModelica.

**Comment by jiwucisha** [comment]
> 是的，我目前正在使用Mworks。我现在有最新版本的Mworks。它包含TYMEDIA库，但媒体文件太少，没有我需要的东西。这个库似乎不太适合Mworks。你已经解决了你遇到的问题吗？你现在还在使用OpenModelica吗？
> 
> > > 我也遇到了同样的问题，你解决了吗？
> > 
> > 
> > 您也在使用Mworks吗？CoolProps库现在已经在Mworks中更新了。您可以下载最新版本看看。这个媒体库与Mworks不太兼容，更适合OpenModelica这样的软件。

I have solved this problem. Due to the incompatibility between the media library and Mworks, you need to modify some of the underlying code and replace the externalmedia.lib with Mworks' lib. Since there are some parts of the code that I cannot modify, I can only replace them with the existing lib of Mworks, and then it will work.
