### ISSUE TITLE
Not possible to compile ExternalMedia/CoolProp for XUbuntu due to missing dependencies

### ISSUE THREAD

**Issue by chermsdorf** [modelica-3rdparty/ExternalMedia#15]
Hello,

I have been trying for a week now to compile ExternalMedia on a fresh Xubuntu 18.04 system in order to be able to use CoolProp with OpenModelica but it seems to be impossible as a lot of dependecies during the installation fail. Please have a look at my [Issue #14](https://github.com/modelica/ExternalMedia/issues/14) to get an idea of what I mean. Although I received very good instructions and hints from Thomas Pedot I did dot manage to complete the compilation.

I would be happy if the instructions in the `CompileHowTwo.txt` file could be updated with instructions that do actually work. Otherwise you might want to inform the community that an installation of ExternalMedia on Linux is no longer supported in order to avoid people from waisting their time. 

Best regards
Christian

**Comment by slamer59** [comment]
Hello,
I succeed to compile CoolProp & ExternalMedia for both Linux / Windows. ExternalMedia seems to work on Linux & OpenModelica (still some issues you can read). And I was able to compile it on Windows with both gcc compiler for OpenModelica and VS compiler for Dymola.

There is a lack of documentation for sure but we try, with our free time, to enhance this. Your questions are more related to your architecture and understand how git/cmake and compilation works together. 

Thanks @casella, @JonWel and @jowr and many others have put many efforts on both projects and may lack some times to answer your needs.

Regards,
Thomas

**Comment by chermsdorf** [comment]
Hi Thomas,

I did not mean to be polemic but at that day I was really frustrated about the non-progess in compiling ExternalMedia for reasons I am not able to identify after having hacked around for a week and I had the feeling that this was related to the fact that the repository was a bit outdated. 

The good news is that you say that you are able to compile the library and make it run with OMC on Linux so I might give it another try. But actually I have no clue where to start since everytime a dependency problem was solved the next error message occured - as you could whitness - and since I am not a software developper I think I will not be able to find the right hacks alone.

Regarding my architecture I cannot evaluate if my fresh Xubuntu 18.04 install is any special. Do you think that might be the case? Which distribution are you using? Could it be that Ubuntu has pre-installed libraries that Xubuntu is missing? Well, I might consider installing Ubuntu then ...

Regarding git and cmake you are right, I have not yet understood how these work together and I find it a bit confusing that there are so many preconfigured BuildLib scripts available theat seem to be almost identical and on the other hand the compilation instructions do not even refer to one of them. But it was a prerequisit to understand all that in detail, than I will most probably not be able to manage that.

Best regards and thank you for your assistance so far
Christian

**Comment by jowr** [comment]
Fixed in v3.3.0
