### ISSUE TITLE
A very specific successful install (coolprop v4 + EM master + dymola) 

### ISSUE THREAD

**Issue by veeshy** [modelica-3rdparty/ExternalMedia#16]
I've seen a lot of issues with compiling EM and thought I'd share a success story, even if it's a bit outdated CP. 

I installed the current EM master (not the dev branch) with coolprop v4.2.4 on Ubuntu 18.04 for use with Dymola 2019. I'll share my build process below, I make no gaurantees but at the least I can confirm that all EM checks pass in dymola.

Download https://github.com/modelica/ExternalMedia/commit/159518edd538b64e28cd70983a9cc47730323cc4
which is the current latest EM on the EM master branch

Download https://sourceforge.net/projects/coolprop/files/CoolProp/4.2.4/

Extract and put the folder in the CoolProp folder (also labeled coolprop) into ExternalMedia//externals/coolprop/trunk/

Navigate to ExternalMedia/Projects and run the linux makefile:

make -f makefile-linux -j40

Once this finishes, you must rename the library folder:

Navigate to ExternalMedia/Modelica/ExternalMedia 3.2.1/Resources/Library

Rename the linux32 folder to linux64

You may now load the package.mo in ExternalMedia/Modelica/ExternalMedia 3.2.1 in dymola 

Sorry this isn't actually an issue..

**Comment by greenwoodms06** [comment]
The one thing that was missing for me to get this to work was I had to update my gcc from the default 5 to 7 (the default for Ubuntu 18) as I was using Ubuntu 16. The steps to do this are below:

1. Get and install the gcc version
    ````
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get install gcc-7 g++-7
    gcc-7 --version
    ````
1. Add to the version controller to easily switch between versions
    ````
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 --slave /usr/bin/g++ g++ /usr/bin/g++-7 
    sudo update-alternatives --config gcc
    ````
1. Now select the gcc version you desire and run `make -f makefile-linux`

**Comment by gganapat** [comment]
Any updates for compiling for OSX (High Sierra)?

**Comment by veeshy** [comment]
Sorry, I haven't tried for OSX, and I jumped to 10.14 where open Modelica won't install via macport right now :(. 

I think the combination of the correct coolprop listed above and building is your best bet though.

**Comment by gganapat** [comment]
> Sorry, I haven't tried for OSX, and I jumped to 10.14 where open Modelica won't install via macport right now :(. Nightly prebuilt works, though I haven't tried EM on it.
> 
> I think the combination of the correct coolprop listed above and building is your best bet though.

Thanks for the quick response! For a novice, is there a cheat sheet that can be useful specifically for OSX build? Looks like the make command covers linux. 
thanks.

**Comment by sjoelund** [comment]
You install macports to get gmake and then make OpenModelica in the same way as on Linux. As long as you don't have the new XCode versions (Apple breaks building the binaries in every single release so we have an OSX 10.9 machine creating binaries which still run on newer OSX versions...)

**Comment by jowr** [comment]
Thanks for sharing the input - I hope v3.3.0 makes this guide obsolete.
