### ISSUE TITLE
Dymola Water - CoolProp - TC Error

### ISSUE THREAD

**Issue by FelixHochwallner** [modelica-3rdparty/ExternalMedia#17]
When using the Media Water - CoolProp - TC I sometimes get a very strange error:
```
The following error was detected at time: 101.9
Number of steps in density_TP has exceeded 30 with inputs T=305.595,p=101325,rho_guess=994.895 for fluid Water
The stack of functions is:
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique15
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique15(sinkP2.p0, condenser.SecondaryFluid.Cells[1].h, 0)
Integration terminated before reaching "StopTime" at T = 102
```
It seems like it does not manage to obtain the density, even though the temperature and pressure are in a fairly normal region and the guess value of the density gives a quite good starting value. Has anyone else experienced this kind of problem? The error vanishes, for example, when using the StandardWater media included in Modelica. Unfortunately I need the Water - CoolProp - TC for the Cell1Dim Component in the Thermocycle Library. 

I am using the newest Thermocycle and External Media Libraries.

Best regards, Felix

**Comment by jowr** [comment]
Without more information this is difficult to reproduce. Please reopen once there are more information.
