### ISSUE TITLE
Outdated TODO in CoolPropSolver::setSat_p?

### ISSUE THREAD

**Issue by beutlich** [modelica-3rdparty/ExternalMedia#20]
There is an open TODO comment in https://github.com/modelica/ExternalMedia/blob/02c6ac398a7cdefe13f4c76b741f0abbd330d3cb/Projects/Sources/coolpropsolver.cpp#L385-L387

That comment is from 2015-07-24, however the referenced issue https://github.com/CoolProp/CoolProp/issues/656 was closed at 2015-07-15, i.e., some days earlier.

@JonWel Can this be fixed now?

**Comment by JonWel** [comment]
Hi,

The `specify_phase` is already uncommented:
https://github.com/modelica/ExternalMedia/blob/02c6ac398a7cdefe13f4c76b741f0abbd330d3cb/Projects/Sources/coolpropsolver.cpp#L390

When I look at this commit, I would guess I removed one, but forgot to remove the second TODO.
https://github.com/modelica/ExternalMedia/commit/f143b8df41cf9699fdb8b2972143eb5ae46d1858#diff-9a10bfb0641604264c302748239a2092

More info on the context can be found here:
https://github.com/CoolProp/ExternalMedia/issues/3

=> I agree with you, the TODO is outdated and shoul be removed.
