### ISSUE TITLE
Cannot compile ExternalMedia under Linux with current CoolProp

### ISSUE THREAD

**Issue by somniumAeternam** [modelica-3rdparty/ExternalMedia#22]
During the build process with the command "make -f makefile-linux header library" or similarly with the script "BuildLib-CMake.sh" the following error occurs:

> cp: der Aufruf von stat für '../externals/CoolProp.build.gcc/CoolProp.dir/Release/*.o' ist nicht möglich: Datei oder Verzeichnis nicht gefunden

(call not possible. File or Folder not found)

So it is compiling but there is no object file or Release folder created.

So I suppose as the ExternalMedia library is outdated, it is not compatible with the new CoolProp. I am not experienced in changing cmake properties etc. in order to make it work again. I would appreciate, if someone can help me to compile this library on linux.

**Comment by casella** [comment]
I'm working on this. Will have time from Sep 12 onwards

**Comment by sgolle** [comment]
#24

**Comment by sgolle** [comment]
Compilation is now working, though the calculation is not successful and shows errors. But this issue is closed.
