### ISSUE TITLE
What version of CoolProp is supported?

### ISSUE THREAD

**Issue by jfulem** [modelica-3rdparty/ExternalMedia#30]
When looking into `CMakeLists.txt` it looks the CoolProp version is set to `5.1.1`. When I try to use `6.4.1` on Windows the compilation fails with the error:
```
CPstrings.h(14): fatal error C1083: Cannot open include file: 'fmt/format.h': No such fil e or directory.
```

**Comment by dongkeun-oh** [comment]
For the version 6, you can add up the following command after the 72nd line of CMakeLists.txt.
```
   list (APPEND INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/../externals/CoolProp.git/externals/fmtlib")
```
That's not fixed yet.

Cheers!

**Comment by jfulem** [comment]
It works, thank you.
