### ISSUE TITLE
Compilation failure when using ExternalMedia

### ISSUE THREAD

**Issue by rtasseno** [modelica-3rdparty/ExternalMedia#35]
Dear,

I am trying to use the ThermoCycle-library. I cannot simulate the examples from this library and I scoped the problem down to issues in the ExternalMedia-library. I cannot simulate any of the examples of this library. I get following error with respect to compiling and linking the model (Visual C++) :

![image](https://user-images.githubusercontent.com/83449490/116677511-98515900-a9a8-11eb-8aa0-cc8d06e31d15.png)

I am using following versions:
- Dymola 2020
- Modelica 3.2.2 / 3.2.3 (tested both)
- Visual Studio 2013/ Visual C++ 2013 Express Edition (12.0)

Has someone encountered this problem before and a possible solution?

Kind regards

**Comment by jowr** [comment]
You are most likely using an incompatible compiler. Have you recompiled ExternalMedia yourself? That should solve the issue.

**Comment by rtasseno** [comment]
The problem was indeed caused by an incompatibility between the ExternalMedia-library and the version of Visual Studio. After installation of VS2012 the problem has been solved. Thank you for your advice!

**Comment by jowr** [comment]
Great - please note that the release from yesterday (v3.3.0) comes with binary files for Visual Studio 2015, 2017 and 2019 in case you prefer a more up-to-date compiler :-)
