### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by JohnHinsley** [modelica-3rdparty/ExternalMedia#40]
Apologies if this is all a bit basic, as I'm new to ExternalMedia, and indeed media as a whole in modelica. I have tried to load and run ExternalMedia 3.3.0 in both OpenModelica and Dymola. On Dymola I can run ExternalMedia.Test.TestMedium.TestBasePropertiesDynamic without problems. On OM I get the following error message:
C:/Program Files/OpenModelica1.17.0-64bit/share/omc/scripts/Compile.bat ExternalMedia.Test.TestMedium.TestBasePropertiesDynamic msvc15 mingw64 parallel 20 0
PATH = "C:\PROGRA~1\OPENMO~1.0-6\tools\msys\mingw64\bin;C:\PROGRA~1\OPENMO~1.0-6\tools\msys\mingw64\bin\..\..\usr\bin;"
mingw32-make: Entering directory 'C:/Users/John/AppData/Local/Temp/OPENMO~1/OMEdit/EXTERN~3.TES'
mingw32-make: Leaving directory 'C:/Users/John/AppData/Local/Temp/OPENMO~1/OMEdit/EXTERN~3.TES'
ExternalMedia.Test.TestMedium.TestBasePropertiesDynamic.makefile:18: *** missing separator.  Stop.
Compilation process failed. Exited with code 2.

The offending line in the makefile is this:   !IF "$(PCH_FILE)" == ""

OM also gives this error:
[1] 18:05:06 Translation Error
[C:/OM117/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFEvalFunction.mo: 181:7-183:92]: Internal error NFEvalFunction.evaluateExternal failed on ExternalMedia.Test.TestMedium.TestBasePropertiesDynamic.Medium.getMolarMass, evaluation of userdefined external functions not yet implemented

Any ideas what I need to tweak to get it to work? Or is it more terminal?

Meanwhile, in Dymola, I wanted to try running ExternalMedia.Test.MSL_Models.IncompressibleFluidNetwork, which says in the description "needs medium definition" so I changed a line to
  replaceable package NewMedium=ExternalMedia.Media.TestMedium;

and now I get this error message when checking the model:

Check of ExternalMedia.Test.MSL_Models.IncompressibleFluidNetwork:

Base class FluidConstants is replaceable
Near file: C:/Program Files/Dymola 2020/Modelica/Library/Modelica 3.2.3/Media/package.mo, line 6328
Context: Modelica.Media.Interfaces.PartialTwoPhaseMedium.FluidConstants.constructor

Must translate function ExternalMedia.Media.TestMedium.setState_pT_Unique26.

Internal error: trying to compile function but did not find it.

Any suggestions?

Once I've got through this beginners pain, I will need to know how to define CoolProps media in this package - I want to use some refrigerants. 
Thanks

**Comment by egroegphysics** [comment]
I'd also be interesting in hearing a bit more about this. #24 and this openmodelica ticket https://trac.openmodelica.org/OpenModelica/ticket/6331 seems to say that it has been fixed if the correct versions of the compilers/openmodelica/this library are used etc. I tried recompiling the code myself and using the pre compiled version and got similar errors to @JohnHinsley . I am particularly interested in openmodelica. Many thanks for your help!

**Comment by egroegphysics** [comment]
I should also add I tried this on linux and windows with similar results

**Comment by casella** [comment]
Folks, apologies, but the whole development team, soon including myself, is off until Aug 16. We'll be back on this.

**Comment by jowr** [comment]
Hi - please note that OpenModelica is not officially supported as this still is work in progress - see #27 for more information.

Please also see https://github.com/modelica-3rdparty/ExternalMedia/milestones for the development roadmap.

**Comment by casella** [comment]
For the status with OpenModelica, see #50. We plan to release 3.3.2 and 4.0.0 in a few weeks.
