### ISSUE TITLE
Build Tools Versioning

### ISSUE THREAD

**Issue by egroegphysics** [modelica-3rdparty/ExternalMedia#41]
Following on from #40 I've had another go compiling the library and whilst I can 'successfully' compile the library a lot of the tests fail for a variety of reasons. I even tried using gcc 7.5 as suggested here with no improvement.

https://github.com/modelica-3rdparty/ExternalMedia/pull/27#issuecomment-833192871

Have also tried some combos of the openmodelica version etc. Do you have a gcc, cmake, openmodelica, ubuntu combination that you know builds and runs the tests successfully? I am particularly interested in super critical CO2. 

Many thanks,

**Comment by egroegphysics** [comment]
Or is there something else I am missing entirely?

**Comment by jowr** [comment]
You can see the automated build process here: https://github.com/modelica-3rdparty/ExternalMedia/blob/master/.github/workflows/ci.yml#L142

Currently, the build system employs the compiler that comes with OpenModelica which is GCC 5.3.0.

I hope that helps.

**Comment by casella** [comment]
The idea is to use the released libraries including all binaries automatically compiled by the GitHub CI. Please try version 3.3.2 or 4.0.0 as soon as they are released.
