### ISSUE TITLE
Upgrade to MSL 4.0.0

### ISSUE THREAD

**Issue by casella** [modelica-3rdparty/ExternalMedia#45]
I just had a discussion with @bilderbuchi and @imkelisa at the Modelica Conference. They have already moved all of their libraries to MSL 4.0.0, so it would be nice to also have ExternalMedia there.

It also doesn't make much sense to develop new funcionaltiy on the MSL 3.2.3 branch.

I would propose that we run the MSL 4.0.0 conversion script and release a version 4.0.0 right away.

We can then have some bugfix versions 3.3.x for critical bugs, but otherwise continue under MSL 4.0.0

@jowr, are you fine with that?

**Comment by bilderbuchi** [comment]
Just to clarify, I was mainly present because of/interested in OpenModelica compatibility; luckily I am not encumbered by many pre-existing libraries/models. :-)

**Comment by imkelisa** [comment]
I did a quick test on converting the library (master branch) to MSL 4.0.0 with Dymola 2022. 
- several incompatible units in test models (time is multiplied e.g. with a pressure to have a varying input)
-in  _ExternalMedia.Media.BaseClasses.ExternalTwoPhaseMedium_ **FluidConstants** is replaceable, in MSL Media 2 phase mediums use an externally defined record for the fluid constants

Not simulating: 
- ExternalMedia.Test.CoolProp.CO2.TestStatesSatSubcritical "T is not a valid number"
- ExternalMedia.Test.CoolProp.Pentane_hs  "Inputs in Brent [143.470000,578.730000] do not bracket the root.  Function values are [6916.155129,60536.779546]
The stack of functions is:
setState_hs_Unique29
setState_hs_Unique29(h, 1500.0, 0)" (last model I tested today)

**Comment by imkelisa** [comment]
Just a comment for Dymola: One has to set Advanced.RelyOnCompiledFunctions=true; in order to prevent Dymola from trying to recompile the external functions (Default behaviour up to Dymola 2018, has been changed after that). See Chapter 5.5.9 in the manual

**Comment by jowr** [comment]
This was closed in 8e37df8b
