### ISSUE TITLE
installing for Openmodelica

### ISSUE THREAD

**Issue by branch171** [modelica-3rdparty/ExternalMedia#47]
Hi

I have run cmake as per compilation instructions and I get a header and library file generated. These are

externalmedialib.h and libExternalMediaLib.a

However, from OMedir after I load the library and try to do a test I get the folling error:

[ExternalMedia.Media.BaseClasses.ExternalTwoPhaseMedium: 198:15-202:26]: External function ‘TwoPhaseMedium_getCriticalPressure_C_impl‘ could not be found in any of the given shared libraries:
  /home/cbranch/Modelica/Libraries/ExternalMedia/Modelica/ExternalMedia 3.3.0/Resources/Library/linux64/libExternalMediaLib.so
  /home/cbranch/Modelica/Libraries/ExternalMedia/Modelica/ExternalMedia 3.3.0/Resources/Library/libExternalMediaLib.so

It seems to be looking for a shared library .so extension and the CMAKE makes a static. Is this the reason for not finding these external functions?

How do I make the CMAKE compile a shared library if that is the solution to the problem?

Also the library is in a folder gcc93 will modelica find it or should I copy up a level into linix64 where it seems to be looking?

**Comment by jowr** [comment]
Hi 

Have you read this section https://github.com/modelica-3rdparty/ExternalMedia/blob/master/README_compilation.md#quick-start-guide? 

In there it says that you can use `cmake --build build --config Release --target install-as-default` to override the compiler specifications and install the libraries to linux64 or linux.


To build a shared library, you can change line 143 in https://github.com/modelica-3rdparty/ExternalMedia/blob/master/Projects/CMakeLists.txt#L143 to 'SHARED' instead of 'STATIC', but that is untested - thank you being the lab mouse here...

**Comment by sjoelund** [comment]
> It seems to be looking for a shared library .so extension and the CMAKE makes a static. Is this the reason for not finding these external functions?

Because OpenModelica can only run functions at compile-time if they are in a shared library (you cannot use `dlopen` on a static library), and it thinks the function must be evaluated because some structural information is returned by the function call.

**Comment by jowr** [comment]
Yes - this is also the reason why the roadmap says that we want to move to shared libraries as the new default. However, we are no there yet.

**Comment by sjoelund** [comment]
> Yes - this is also the reason why the roadmap says that we want to move to shared libraries as the new default. However, we are no there yet.

I would compile both static (with -fPIC) and shared, so the library can be linked into an FMU without problem as well (so many issues with FMUs not finding its dependencies).

**Comment by branch171** [comment]
Hi

The change to SHARED on line 143 did not work. There is an issue with CoolProp.

/usr/bin/ld: CoolProp/CMakeFiles/CoolProp.dir/src/CoolPropTools.cpp.o: relocation R_X86_64_TPOFF32 against `_ZL10ftw_summer' can not be used when making a shared object; recompile with -fPIC

**Comment by branch171** [comment]
This can now be closed. You need to do the following

69 SET(COOLPROP_STATIC_LIBRARY OFF CACHE BOOL "Force the static library")
70 SET(COOLPROP_SHARED_LIBRARY ON CACHE BOOL "Force the shared library")
71 SET(COOLPROP_OBJECT_LIBRARY OFF  CACHE BOOL "Force the object library")

143 add_library(${LIBRARY_NAME} SHARED ${LIB_SOURCES})
147 target_compile_definitions(${LIBRARY_NAME} PRIVATE EXTERNALMEDIA_MODELICA_ERRORS=0) # Use 0 for a shared library and 1 for a static library

With these changes the shared library compiles and runs the examples in OpenModelica
