### ISSUE TITLE
Cross Compilation with CMake

### ISSUE THREAD

**Issue by slamer59** [modelica-3rdparty/ExternalMedia#5]
Cmake is designed to build, test and package software.
Add a cmake to streamline the code generation for multiple platforms is an approach

CoolProp developpement shows [how to build static library from it](http://www.coolprop.org/dev/coolprop/wrappers/StaticLibrary/index.html#cmake-integration)

The same approach [can be seen here](https://github.com/CoolProp/ExternalMedia/tree/master/Projects)

Compiled library will be installed in  **Resources/Library** following suggestion https://github.com/modelica/ExternalMedia/issues/4#issuecomment-345747096.

**Comment by jowr** [comment]
I guess this one is obsolete soon since #6 already contains my changes that introduced CMake. However, my code was written in a hurry and I would appreciate if you had a look at it.

**Comment by slamer59** [comment]
It is a good starting point to reach the objective by the end of the year. 

For an enhancement, all commands in .bat file and .sh in **ExternalMedia/Projects/** may be integrated in CMakeLists.txt. It will be easier to maintain one file for cmake than 10 specific files for specific compilation. 

We can build a more robust cross compilation process integrating all those command in CMake:
- FindGit.cmake helps to find git and will replace all commands like **git clone**, **git pull**,...
- CFLAGS will replace for example C_OPTS, i.e. GCC_OPTS, variable in .bat file, .i.e .sh file
- file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/ DESTINATION ${CMAKE_CURRENT_BINARY_DIR}) to replace **copy** or **cp** command
- ...

I guess all specific compilation option will be handle by hand or by TravisCI system.

**Comment by jowr** [comment]
Yes, but we still have to decide whether we want to use CoolProp as a submodule in git or as an external CMake project (ExternalProject_Add). I think we should try to avoid calling git manually :-)

**Comment by slamer59** [comment]
@jowr, I think this is not related to CMake
So I open a specific subject #8
