### ISSUE TITLE
Integer state.phase not returned correctly in OpenModelica

### ISSUE THREAD

**Issue by casella** [modelica-3rdparty/ExternalMedia#55]
Run `ExternalMedia.Test.TestMedium.TestState` with the latest nightly build of OpenModelica.

The simulation runs successfully and produces the expected results for all the real variables of the state record. However, the phase value, which is supposed to be an integer equal to one, is returned as zero at the initial time and then as 6.2148e12.

This is probably a bug in OpenModelica that needs to be investigated and fixed, see [OMC #8591](https://github.com/OpenModelica/OpenModelica/issues/8591)

**Comment by bilderbuchi** [comment]
With current EM master and OM 1.20 `state.phase` has the value 1 for the whole simulation period, so I think this can be closed.

**Comment by casella** [comment]
Absolutely, OpenModelica/OpenModelica#8591 was fixed, so this can be closed for good. Thanks @bilderbuchi for pointing out!
