### ISSUE TITLE
Compilation failure in Dymola 2021

### ISSUE THREAD

**Issue by congtoantran** [modelica-3rdparty/ExternalMedia#58]
Dear, 

I am trying to use ExternalMedia, but when testing the example of that library I get the following error . 

![Capture d’écran 2022-03-28 144600](https://user-images.githubusercontent.com/88037828/160401030-d6db682d-d5be-400b-a2ee-7839518cfa7b.png)

I'm using the following versions: 

- Dymola 2021
- Modelica 4.0.0
- Visual Studio 2019/ Visual C++ 2019 (16)

I've downloaded ExternalMedia (branch MSL4.0), run the file "BuildLib-Dymola-VS2019.bat", then the 2 file .lib (ExternalMediaLib.Dymola-vs2019 and ExternalMediaLib) have been well created. 

Thank you for your help, 

Regards,

**Comment by casella** [comment]
@congtoantran we are working to make the dynamically linked version to run fine, see #50. We'll release a 4.0.0 version immediately after that. If you need one right now, you may try to take 3.3.1 and run conversion scripts on it.

**Comment by casella** [comment]
See also #62. We're almost done 😃

**Comment by casella** [comment]
Everything should now work out of the box with version 3.3.2, due anytime soon, and 4.0.0. You can get a pre-release of 3.3.2 in the binaries [here](https://github.com/modelica-3rdparty/ExternalMedia/actions/runs/4682008365).
