### ISSUE TITLE
sCO2 from CoolProp failing in compressor model

### ISSUE THREAD

**Issue by shigrekar1** [modelica-3rdparty/ExternalMedia#59]
Hello,
I am trying to set up a sCO2 Brayton cycle using the ExternalMedia package, however, the sCO2 fluid causes failure in my turbomachinery components. Provided below is the error text. 

I wanted to know if this is related to the fluid package or something else.

Thank you.

Error text:

Log-file of program ./dymosim
(generated: Sat Apr  9 15:47:42 2022)

dymosim started
... "Unnamed4" simulating
... "dsin.txt" loading (dymosim input file)
Error: The following error was detected at time: 0
Invalid values for inputs p=100000 h=0 for fluid CarbonDioxide
The stack of functions is:
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6(100000.0, Comp1.gas_iso.h, 0)
ExternalMedia.Media.CoolPropMedium.temperature_ph_Unique21(Comp1.gas_iso.p, Comp1.gas_iso.h, Comp1.gas_iso.phaseInput)

First evaluation failed for non-linear solver.

Error: The following error was detected at time: 0
Invalid values for inputs p=100000 h=0 for fluid CarbonDioxide
The stack of functions is:
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6(100000.0, Comp1.gas_iso.h, 0)
ExternalMedia.Media.CoolPropMedium.temperature_ph_Unique21(Comp1.gas_iso.p, Comp1.gas_iso.h, Comp1.gas_iso.phaseInput)

Non-linear solver will attempt to handle this problem.

Error: The following error was detected at time: 0
Invalid values for inputs p=100000 h=1e-08 for fluid CarbonDioxide
The stack of functions is:
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6(100000.0, Comp1.gas_iso.h, 0)
ExternalMedia.Media.CoolPropMedium.temperature_ph_Unique21(Comp1.gas_iso.p, Comp1.gas_iso.h, Comp1.gas_iso.phaseInput)

Non-linear solver will attempt to handle this problem.

Warning: Failed to solve nonlinear system using Newton solver.
  During initialization at time: 0
  Tag: initialization.nonlinear[2]
  For debugging information enable
  Simulation/Setup/Debug/Nonlinear solver diagnostics/Detailed logging of failed nonlinear solutions.
Error: Integrator failed to start model.

ERROR: The simulation of Unnamed4 FAILED

**Comment by imkelisa** [comment]
Did you provide a start value for h in your component?

**Comment by casella** [comment]
@shigrekar1 I think @imkelisa's comments is spot on. Please reopen with more info if you can't fix this.
