### ISSUE TITLE
externalMedia3.3.1 not working with openmodelica 1.18.1

### ISSUE THREAD

**Issue by denis-jidovtseff-jc** [modelica-3rdparty/ExternalMedia#60]
I can't get a complete working ExternalMedia library working with openModelica
I working with openModelica 1.18.1 with OM simulator 2.1.1
compilator Mingw ( from openmodelica installer)
with the zipped version of ExternalMedia 3.3.1

I'm havig the following errors when running for example the TestStatesSat test

[1] 10:24:58 Traduction Erreur
[ExternalMedia.Media.BaseClasses.ExternalTwoPhaseMedium: 186:15-190:19]: External function ‘TwoPhaseMedium_getMolarMass_C_impl‘ could not be found in any of the given shared libraries:
  C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Library/win64/ExternalMediaLib.dll
  C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Library/ExternalMediaLib.dll

[2] 10:24:58 Traduction Erreur
[ExternalMedia.Media.BaseClasses.ExternalTwoPhaseMedium: 198:15-202:26]: External function ‘TwoPhaseMedium_getCriticalPressure_C_impl‘ could not be found in any of the given shared libraries:
  C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Library/win64/ExternalMediaLib.dll
  C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Library/ExternalMediaLib.dll

and this from the compiler

`TestStatesSat_functions.c:113:42: warning: incompatible pointer types passing 'ExternalMedia_Test_TestMedium_TestStatesSat_Medium_SaturationProperties *' to parameter of type 'ExternalSaturationProperties *' (aka 'struct ExternalSaturationProperties *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setSat_T_C_impl(_T_ext, &_sat_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                         ^~~~~~~~~
C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:197:99: note: passing argument to parameter 'sat' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setSat_T_C_impl(double T, ExternalSaturationProperties *sat, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                         ^
TestStatesSat_functions.c:153:42: warning: incompatible pointer types passing 'ExternalMedia_Test_TestMedium_TestStatesSat_Medium_SaturationProperties *' to parameter of type 'ExternalSaturationProperties *' (aka 'struct ExternalSaturationProperties *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setSat_p_C_impl(_p_ext, &_sat_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                         ^~~~~~~~~
C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:196:99: note: passing argument to parameter 'sat' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setSat_p_C_impl(double p, ExternalSaturationProperties *sat, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                         ^
TestStatesSat_functions.c:196:53: warning: incompatible pointer types passing 'ExternalMedia_Test_TestMedium_TestStatesSat_Medium_ThermodynamicState *' to parameter of type 'ExternalThermodynamicState *' (aka 'struct ExternalThermodynamicState *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setState_pT_C_impl(_p_ext, _T_ext, &_state_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                                    ^~~~~~~~~~~
C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:171:110: note: passing argument to parameter 'state' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setState_pT_C_impl(double p, double T, ExternalThermodynamicState *state, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                                    ^
TestStatesSat_functions.c:247:65: warning: incompatible pointer types passing 'ExternalMedia_Test_TestMedium_TestStatesSat_Medium_ThermodynamicState *' to parameter of type 'ExternalThermodynamicState *' (aka 'struct ExternalThermodynamicState *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setState_ph_C_impl(_p_ext, _h_ext, _phase_ext, &_state_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                                                ^~~~~~~~~~~
C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:170:121: note: passing argument to parameter 'state' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setState_ph_C_impl(double p, double h, int phase, ExternalThermodynamicState *state, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                                               ^
TestStatesSat_functions.c:349:65: warning: incompatible pointer types passing 'ExternalMedia_Test_TestMedium_TestStatesSat_completeBubbleDewStates1_Medium_ThermodynamicState *' (aka 'ExternalMedia_Test_TestMedium_TestStatesSat_Medium_ThermodynamicState *') to parameter of type 'ExternalThermodynamicState *' (aka 'struct ExternalThermodynamicState *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setState_ph_C_impl(_p_ext, _h_ext, _phase_ext, &_state_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                                                ^~~~~~~~~~~
C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:170:121: note: passing argument to parameter 'state' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setState_ph_C_impl(double p, double h, int phase, ExternalThermodynamicState *state, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                                               ^
TestStatesSat_functions.c:416:9: error: use of undeclared identifier '_completeBubbleDewStates1'
  _MM = _completeBubbleDewStates1._bubbleStateOnePhase._Medium._externalFluidConstants._molarMass;
        ^
TestStatesSat_functions.c:523:9: error: use of undeclared identifier '_completeBubbleDewStates1'
  _MM = _completeBubbleDewStates1._bubbleStateTwoPhase._Medium._externalFluidConstants._molarMass;
        ^
TestStatesSat_functions.c:630:9: error: use of undeclared identifier '_completeBubbleDewStates1'
  _MM = _completeBubbleDewStates1._dewStateOnePhase._Medium._externalFluidConstants._molarMass;
        ^
TestStatesSat_functions.c:737:9: error: use of undeclared identifier '_completeBubbleDewStates1'
  _MM = _completeBubbleDewStates1._dewStateTwoPhase._Medium._externalFluidConstants._molarMass;
        ^
TestStatesSat_functions.c:879:65: warning: incompatible pointer types passing 'ExternalMedia_Test_TestMedium_TestStatesSat_completeBubbleDewStates2_Medium_ThermodynamicState *' (aka 'ExternalMedia_Test_TestMedium_TestStatesSat_Medium_ThermodynamicState *') to parameter of type 'ExternalThermodynamicState *' (aka 'struct ExternalThermodynamicState *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setState_ph_C_impl(_p_ext, _h_ext, _phase_ext, &_state_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                                                ^~~~~~~~~~~
C:/Users/be92251/Downloads/ExternalMedia_v3.3.1/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:170:121: note: passing argument to parameter 'state' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setState_ph_C_impl(double p, double h, int phase, ExternalThermodynamicState *state, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                                               ^
TestStatesSat_functions.c:946:9: error: use of undeclared identifier '_completeBubbleDewStates2'
  _MM = _completeBubbleDewStates2._bubbleStateOnePhase._Medium._externalFluidConstants._molarMass;
        ^
TestStatesSat_functions.c:1053:9: error: use of undeclared identifier '_completeBubbleDewStates2'
  _MM = _completeBubbleDewStates2._bubbleStateTwoPhase._Medium._externalFluidConstants._molarMass;`

Can someone explain me how to run it without errors on openmodelica?

Many thanks

**Comment by casella** [comment]
@denis-jidovtseff-jc we have fixed several issue in OMC preventing it to work correctly with ExternalMedia. There are still a few more, see #50. We should hopefully release ExternalMedia 3.3.2 and 4.0.0 in a few weeks, and then it should work with the latest nightly build of OMC. Older versions can't do that.
