### ISSUE TITLE
Remove the version number from the directory name of the Modelica source code

### ISSUE THREAD

**Issue by jowr** [modelica-3rdparty/ExternalMedia#63]
Remove the version number from the directory name of the Modelica source code directory, because that requires changing all the file names every time a new version is released. We could make without it, or possibly change the build script to copy all the required files on a build directory where the version number is added to the Modelica directory name, if that is not too difficult

**Comment by casella** [comment]
Fixed on the [dynamiclib](https://github.com/modelica-3rdparty/ExternalMedia/tree/dynamiclib) branch, will be merged to master prior to the next release
