### ISSUE TITLE
The problem when using setState_pT funtion to return ThermodynamicState

### ISSUE THREAD

**Issue by zbb2022hust** [modelica-3rdparty/ExternalMedia#69]
Hello, I met some problem when I used funtion to calculate ThermodynamicState.
At first, I tried to run a example on MWorks as shown below, but an error came out when translating codes.
![image](https://user-images.githubusercontent.com/61374634/198197165-ce878e1b-5059-4ef1-89bc-4cec35cca2b0.png)
![image](https://user-images.githubusercontent.com/61374634/198196971-e31a3a82-e201-4163-a657-e9801bce9753.png)
The error means the members of record funtion have different variability. Actually, I don't understand this error.
But I tried another example as shown below. The same error occurred but this example could work on OpenModelica.
![image](https://user-images.githubusercontent.com/61374634/198198373-855346fc-ac58-49e9-8a03-5933ae461f4f.png)
![image](https://user-images.githubusercontent.com/61374634/198198450-497b2e1b-1f4f-47b2-8c46-1776e0c8dff2.png)
I wonder know why this different results came up on different platforms and how to solve this problem. I really need to use 
ExternalMedia to get refrigerant properities in my model. 
Thanks!

**Comment by zbb2022hust** [comment]
By the way, I ran this example in Dymola2023. Error occurred when compiling model.I used VC ++ 14.29 in Dymola and mingw64 in MWorks and OM.
![image](https://user-images.githubusercontent.com/61374634/198918095-f9b3c091-10a3-4e98-828d-164860a61a5d.png)

**Comment by casella** [comment]
@zbb2022hust everything should be fixed now for Dymola, you can try with the binaries [here](https://github.com/modelica-3rdparty/ExternalMedia/actions/runs/4682008365) until we do the official release. Please reopen if you still have issues with Dymola and/or with MWorks.
