### ISSUE TITLE
ExternalMedia with OpenModelica: dlls not found

### ISSUE THREAD

**Issue by maho7000** [modelica-3rdparty/ExternalMedia#70]
Hello, I started using OpenModelica and wanted to set-up a cycle simulation with CO2 as working medium. Therefore, I downloaded ExternalMedia v3.3.1 and loaded the package.mo. However, I get the following error when I test e.g. CO2Coolprop:

[ExternalMedia.Media.BaseClasses.ExternalTwoPhaseMedium: 186:15-190:19]: External function ‘TwoPhaseMedium_getMolarMass_C_impl‘ could not be found in any of the given shared libraries:
  C:/sw/OpenModelica1.19.2-64bit/bin/ExternalMediaLib.dll
  D:/Users/ikemhofe/Documents/Modelica/ExternalMedia 3.3.1/Resources/Library/mingw64/ExternalMediaLib.dll
  D:/Users/ikemhofe/Documents/Modelica/ExternalMedia 3.3.1/Resources/Library/win64/ExternalMediaLib.dll
  D:/Users/ikemhofe/Documents/Modelica/ExternalMedia 3.3.1/Resources/Library/ExternalMediaLib.dll
  C:/sw/OpenModelica1.19.2-64bit/bin/libExternalMediaLib.dll
  D:/Users/ikemhofe/Documents/Modelica/ExternalMedia 3.3.1/Resources/Library/mingw64/libExternalMediaLib.dll
  D:/Users/ikemhofe/Documents/Modelica/ExternalMedia 3.3.1/Resources/Library/win64/libExternalMediaLib.dll
  D:/Users/ikemhofe/Documents/Modelica/ExternalMedia 3.3.1/Resources/Library/libExternalMediaLib.dll
  C:/sw/OpenModelica1.19.2-64bit/bin/ffi/ExternalMediaLib.dll
  C:/sw/OpenModelica1.19.2-64bit/bin/ffi/libExternalMediaLib.dll

I checked the folders and found only *.lib files. Therefore, my question is: where are the dll-files?
Compiling ExternalMedia myself as described in the manual did not help either, since this gave me the same *.lib file.

When I try to simulate ExternalMedia.Test.CoolProp.CO2.TestStatesSupercritical OpenModelica just crashes.

Can you please help me?

Best regards,
Markus

**Comment by casella** [comment]
@maho7000 please try with the latest 3.3.2 version of the library. It's going to be released soon, in the meantime you can use the binaries you can get [here](https://github.com/modelica-3rdparty/ExternalMedia/actions/runs/4682008365).
