### ISSUE TITLE
Unfortunate default values

### ISSUE THREAD

**Issue by rfranke** [modelica-3rdparty/ExternalMedia#75]
The following model fails to translate in OpenModelica
```Modelica
model MediumDefaults
  package Medium = ExternalMedia.Examples.CO2CoolPropTabular;
  Medium.Temperature T = Medium.T_default;
  Medium.AbsolutePressure p = Medium.p_default;
  Medium.SpecificEnthalpy h = Medium.h_default;
end MediumDefaults;
```
with the error message
```
Error
ExternalMedia error: inputs are not in range, p=101325 Pa, T=293.15 K
Translation Error
[ExternalMedia.Media.BaseClasses.ExternalTwoPhaseMedium: 575:5-575:93]: [Failed to evaluate function: MediumDefaults.Medium.setState_pT_noErr.]
```
This appears to be caused by `ExternalTwoPhaseMedium` defining `h_default = specificEnthalpy_pT_noErr(p_default, T_default)`.
```Modelica
within ExternalMedia.Media.BaseClasses;

package ExternalTwoPhaseMedium "Generic external two phase medium package"
  extends Modelica.Media.Interfaces.PartialTwoPhaseMedium(
    singleState = false, onePhase = false, smoothModel = false, fluidConstants = {externalFluidConstants},
    h_default = specificEnthalpy_pT_noErr(p_default, T_default));
...
```
The model works when setting `p_default` to just above the triple point pressure of 517964.34344772575 Pa (see 
http://www.coolprop.org/fluid_properties/fluids/CarbonDioxide.html), e.g. to 517965.

This error is particularly unfortunate as many fluid models use Medium defaults as start values that may not even play a role in the simulation later on -- but let the translation fail when evaluating them.

Do libraries like CoolProp possibly provide reasonable default values?

Something that could be added to `CoolPropMedium` like:
```Modelica
within ExternalMedia.Media;

package CoolPropMedium "Medium package accessing the CoolProp solver"
  extends BaseClasses.ExternalTwoPhaseMedium(final libraryName = "CoolProp",
    final substanceName = ExternalMedia.Common.CheckCoolPropOptions(substanceNames[1], debug = false),
    p_default = coolPropGet_p_default(substanceName),
    T_default = coolPropGet_T_default(substanceName));
);
```
This way also the custom start value for SpecificEnthalpy of 2e5 could possibly be removed:
```Modelica
  package CO2CoolPropTabular "CoolProp model of CO2 using tabulated data and bicubic interpolation"
    extends ExternalMedia.Media.CoolPropMedium(mediumName = "CarbonDioxide", substanceNames = {"CO2|enable_BICUBIC=1"}, ThermoStates = Modelica.Media.Interfaces.Choices.IndependentVariables.ph,
    SpecificEnthalpy(start = 2e5));
  end CO2CoolPropTabular;
```

**Comment by casella** [comment]
I'm not aware of anything like "default values" in CoolProp. In fact, the default values could need to be re-defined by the user based on the specific field of application of the fluid model.

That said, I fully agree that since Modelica.Media defines those values, computing them should cause no error. Maybe using exactly the critical pressure is a bit dangerous, if you get close to the critical point the h(p,T) function has nearly singular behaviour. We could either use, say, 1.5*pcrit or 0.5*pcrit. 

@rfranke what do you think?

**Comment by casella** [comment]
BTW, I tried you MediumDefaults test with the latest build [here](https://github.com/modelica-3rdparty/ExternalMedia/actions/runs/4682008365), and it runs fine, though it computes h_default = 0. Which version were you using?

**Comment by casella** [comment]
In any case, cb18332 fixes the problem. Thanks for reporting!

**Comment by rfranke** [comment]
Thank you for the fix @casella! I was using the version of the master branch and built `libExternalMediaLib.so.3.3.2` with the commands `cmake; make` under Ubuntu. `h_default=0` is strange.
```
p_default = 0.5*p_critical
```
sounds reasonable. Resulting in about 37 bar for CO2 and 110 bar for water. CoolProp also offers p_triple (and T_triple) allowing something like
```
p_default = 0.5*(p_triple + p_critical)
```
But this hardly changes anything for the two examples and would require an extension of the ExternalMedia C interface.
