### ISSUE TITLE
Debugging issue with openModelica

### ISSUE THREAD

**Issue by denis-jidovtseff-jc** [modelica-3rdparty/ExternalMedia#77]
When I simulate a model with the debugger with openModelica I have an error message
`Impossible to execute the code, because ExternalMediaLib.dll is unfindable, the reinstallation of the software can solve this problem`

the library is well installed with version 3.3.1 (converted to moelica4.0)

**Comment by casella** [comment]
We are going to release 3.3.2 and 4.0.0 anytime soon. You can try 3.3.2 from the binaries [here](https://github.com/modelica-3rdparty/ExternalMedia/actions/runs/4682008365).

**Comment by denis-jidovtseff-jc** [comment]
this is the same issue with the  3.3.2

**Comment by casella** [comment]
@denis-jidovtseff-jc  would you mind opening a ticket on OpenModelica about that?
