### ISSUE TITLE
C99 comments

### ISSUE THREAD

**Issue by thorade** [modelica-3rdparty/ExternalMedia#81]
According to MLS spec C89 should be used:
https://specification.modelica.org/v3.4/Ch12.html#external-function-interface
Modelon Impact uses gcc with -std=c89 and complains about the C99 comments.
I will send a PR to fix it

**Comment by bilderbuchi** [comment]
Would Impact notice an `external "C99"` usage and adjust its flags accordingly?

Spec: 
>The language-specification must currently be one of "builtin" (deprecated), "C", "C…" (for one of the specific C standards like C89, C99, and C11 – specifying that it relies on the C standard library of that version) or "FORTRAN 77". Unless the external language is specified, it is assumed to be "C".
>
>[The intended use of, e.g., C99 is to detect if the user tries to link with a C99-function using a C89 compiler.]
