### ISSUE TITLE
Use CoolProp 6.4.4 as soon as it is released, instead of nightly build

### ISSUE THREAD

**Issue by casella** [modelica-3rdparty/ExternalMedia#84]
ExternalMedia currently uses an unreleased version of CoolProp 6.4.4 which includes an important fix for @fedetftpolimi.

As soon as CoolProp 6.4.4 (or later) is released, we should replace it and rebuild ExternalMedia.

**Comment by jowr** [comment]
Heads up - I just released CoolProp v6.5.0.
