### ISSUE TITLE
Wrong version of cmake required to compile the library

### ISSUE THREAD

**Issue by Ellignham** [modelica-3rdparty/ExternalMedia#89]
Hi,

I was trying to compile ExternalMedia (both version 3.3.2 and 4.0.0) on Linux (Debian10) .

An issue I encountered is the required version of cmake : I was using version 3.13.4 and in the file "/Projects/CMakeLists.txt" the first line requires version 2.8.12 `cmake_minimum_required(VERSION 2.8.12 FATAL_ERROR)`.

In the same file there is an instruction on line 71 `file(ARCHIVE_EXTRACT INPUT ${CMAKE_BINARY_DIR}/coolprop.zip)` the instruction `file(ARCHIVE_EXTRACT ...)` doesn't seem to exist in cmake versions prior to 3.18.6.

I think the required version of cmake should be updated. I managed to compile with cmake version 3.26.3 but I haven't tested with other versions.

Thanks in advance,

Pierre

**Comment by efokken-abb** [comment]
In case that is interesting, I'm working on a pull request that can reduce the needed cmake version to 3.9.

Also for finding out exactly, which cmake version is needed I can recommend the tool

https://github.com/nlohmann/cmake_min_version
