### ISSUE TITLE
build error using cmake on windows

### ISSUE THREAD

**Issue by imkelisa** [modelica-3rdparty/ExternalMedia#92]
Hi, I haven't been able to build the ExternalMedia with the most recent CoolProp versions, it seems that format.h was moved to another directory in the CoolProp repository. 
The build works fine if I switch off the CoolProp integration. 
 
![image](https://github.com/modelica-3rdparty/ExternalMedia/assets/27726784/0552cc83-b1b0-4a11-95cb-4d0b1205cb5f)

**Comment by jowr** [comment]
This is fixed in #91  - maybe I should just merge that PR...
